language: objective-c
osx_image: xcode9
branches:
  only:
    - master
env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
  - IOS_FRAMEWORK_SCHEME="Filestack"
  - NSUnbufferedIO=YES
  matrix:
    - DESTINATION="OS=10.3.1,name=iPhone 7 Plus"   SCHEME="$IOS_FRAMEWORK_SCHEME"
    - DESTINATION="OS=9.3,name=iPhone 6"           SCHEME="$IOS_FRAMEWORK_SCHEME"
    - DESTINATION="OS=9.0,name=iPhone 5"           SCHEME="$IOS_FRAMEWORK_SCHEME"
before_install:
  - brew install carthage
  - carthage bootstrap --no-build --use-submodules --verbose
script:
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -showsdks
  - carthage version

  # Build Framework in Debug and Run Tests
  - xcodebuild -scheme "$SCHEME" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO ENABLE_TESTABILITY=YES clean build build-for-testing | xcpretty;
  - travis_retry xcodebuild -scheme "$SCHEME" -destination "$DESTINATION" -configuration Debug test-without-building | xcpretty;

after_success:
   - sleep 5
